import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import pg from 'pg';
import { createAuth, digest } from '../src/auth.mjs';
import { createApp } from '../src/app.mjs';

test('real PostgreSQL: upgrades, invitations, concurrent redemption, identity and HTTP sessions', { skip: !process.env.TEST_DATABASE_URL, timeout: 60000 }, async () => {
  const control = new pg.Pool({ connectionString: process.env.TEST_DATABASE_URL });
  let pool, app;
  const schema = `auth_${randomUUID().replaceAll('-', '')}`;
  let created = false;
  try {
    const { rows } = await control.query('SELECT current_database() AS name');
    assert.match(rows[0].name, /^pimesh_test_/, 'Refuse non-test databases before any write');
    await control.query(`CREATE SCHEMA ${schema}`); created = true;
    pool = new pg.Pool({ connectionString: process.env.TEST_DATABASE_URL, options: `-c search_path=${schema}` });
    const directory = new URL('../migrations/', import.meta.url);
    await pool.query(readFileSync(new URL('001-directory.sql', directory), 'utf8'));
    await pool.query("INSERT INTO users(user_id,email,display_name) VALUES ('legacy','legacy@example.test','Legacy fixture')");
    await pool.query("INSERT INTO teams(team_id,name,created_by) VALUES ('00000000-0000-0000-0000-000000000001','Fixture','legacy')");
    const migrate = async () => { for (const name of readdirSync(directory).filter((n) => n.endsWith('.sql')).sort()) await pool.query(readFileSync(new URL(name, directory), 'utf8')); };
    await migrate(); await migrate();
    assert.equal((await pool.query('SELECT created_by FROM teams')).rows[0].created_by, 'legacy');
    const auth = createAuth(pool);
    const make = async () => (await auth.generate({}))[0];
    const password = 'Synthetic-fixture-password-123';
    const input = (invite, username = 'alice', email = `${username}@example.test`) => ({ invite, username, email, password });
    const first = await make();
    const user = await auth.register(input(first.code, 'Alice', 'ALICE@example.test'));
    assert.match(user.user_id, /^[a-f0-9-]{36}$/); assert.equal(user.username, 'alice'); assert.equal(user.email_verified, false);
    assert.ok(!('password_hash' in user));
    await assert.rejects(auth.register(input(first.code, 'other')), { code: 'invalid_invite' });
    const second = await make();
    await assert.rejects(auth.register(input(second.code, 'ALICE', 'different@example.test')), { code: 'account_unavailable' });
    await assert.rejects(auth.register(input(second.code, 'different', 'Alice@example.test')), { code: 'account_unavailable' });
    await auth.register(input(second.code, 'bob'));
    const revoked = await make(); await auth.revoke(revoked.invite_id);
    await assert.rejects(auth.register(input(revoked.code, 'revoked')), { code: 'invalid_invite' });
    const expired = await make();
    await pool.query("UPDATE registration_invites SET expires_at=now()-interval '1 second' WHERE invite_id=$1", [expired.invite_id]);
    await assert.rejects(auth.register(input(expired.code, 'expired')), { code: 'invalid_invite' });
    const concurrent = await make();
    const results = await Promise.allSettled([auth.register(input(concurrent.code, 'racer_one')), auth.register(input(concurrent.code, 'racer_two'))]);
    assert.equal(results.filter((r) => r.status === 'fulfilled').length, 1);
    assert.equal(results.find((r) => r.status === 'rejected').reason.code, 'invalid_invite');
    const listed = await auth.invites(); assert.ok(listed.every((r) => !('code_hash' in r) && !('code' in r)));
    await assert.rejects(auth.login({ login: 'missing', password }), { code: 'invalid_credentials' });
    await assert.rejects(auth.login({ login: 'alice', password: 'wrong' }), { code: 'invalid_credentials' });
    await assert.rejects(auth.login({ login: 'legacy', password }), { code: 'invalid_credentials' });
    const session = await auth.login({ login: 'ALICE@example.test', password });
    assert.equal((await auth.me(session.token)).user_id, user.user_id);
    assert.equal((await pool.query('SELECT token_hash FROM auth_sessions')).rows[0].token_hash, digest(session.token));
    await auth.logout(session.token); await assert.rejects(auth.me(session.token), { status: 401 });
    const stale = await auth.login({ login: 'alice', password });
    await pool.query("UPDATE auth_sessions SET expires_at=now()-interval '1 second'");
    await assert.rejects(auth.me(stale.token), { status: 401 });
    const disabled = await auth.login({ login: 'bob', password });
    await pool.query("UPDATE users SET status='disabled' WHERE username='bob'");
    await assert.rejects(auth.me(disabled.token), { status: 401 });
    await assert.rejects(auth.login({ login: 'bob', password }), { status: 401 });
    app = createApp(pool, { authEnabled: true, publicOrigin: 'https://example.test',
      adminHash: digest('admin:synthetic-password'), accessHash: digest('viewer:synthetic-password'), dashboardEnabled: true });
    app.listen(0, '127.0.0.1'); await once(app, 'listening');
    const base = `http://127.0.0.1:${app.address().port}`;
    const headers = { 'Content-Type': 'application/json', 'X-PiMesh-Request': '1', Origin: 'https://example.test' };
    const post = (path, data, extra = {}) => fetch(base + path, { method: 'POST', headers: { ...headers, ...extra }, body: JSON.stringify(data) });
    const admin = { Authorization: 'Basic ' + Buffer.from('admin:synthetic-password').toString('base64') };
    const generated = await post('/api/v1/admin/invites', { count: 2 }, admin); assert.equal(generated.status, 201);
    const codes = (await generated.json()).items;
    const registered = await post('/api/v1/auth/register', input(codes[0].code, 'http_user')); assert.equal(registered.status, 201);
    const logged = await post('/api/v1/auth/login', { login: 'http_user', password }); assert.equal(logged.status, 200);
    const setCookie = logged.headers.get('set-cookie');
    for (const flag of ['__Host-meshpi_session=', 'HttpOnly', 'Secure', 'SameSite=Strict', 'Path=/']) assert.ok(setCookie.includes(flag));
    const Cookie = setCookie.split(';')[0];
    assert.equal((await fetch(base + '/api/v1/auth/me', { headers: { Cookie } })).status, 200);
    assert.equal((await fetch(base + '/api/v1/directory/summary', { headers: { Cookie } })).status, 401);
    assert.equal((await post('/api/v1/admin/invites', {}, { Cookie })).status, 401);
    assert.equal((await post(`/api/v1/admin/invites/${codes[1].invite_id}/revoke`, {}, admin)).status, 200);
    assert.equal((await post('/api/v1/auth/logout', {}, { Cookie })).status, 200);
    assert.equal((await fetch(base + '/api/v1/auth/me', { headers: { Cookie } })).status, 401);
  } finally {
    if (app) await new Promise((resolve) => app.close(resolve));
    if (pool) await pool.end();
    if (created) await control.query(`DROP SCHEMA ${schema} CASCADE`);
    await control.end();
  }
});
